FROM mcr.microsoft.com/devcontainers/dotnet:7.0-jammy

COPY Scripts/create-dot-net-devcert/common.sh /opts/scr/Scripts/create-dot-net-devcert/common.sh
COPY Scripts/create-dot-net-devcert/ubuntu.sh /opts/scr/Scripts/create-dot-net-devcert/ubuntu.sh
RUN /opts/scr/Scripts/create-dot-net-devcert/ubuntu.sh